// @generated by `lake env lean tools/ToRust.lean` from
// `Mempipe/Program.lean` (`SPc`, `sprog`, `RPc`, `rprog`). Do not edit.

use core::sync::atomic::Ordering;

use crate::{Pipe, Status};

/// Sender program counter. `k` is the index of the message being sent, `b`
/// whether this send blocks, `i` a buffer index.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SPc {
    /// Start message `k`: halt if all `M` are sent, else choose `blocking`.
    Start { k: usize },
    /// `alloc_buffer`: `client_owned[i].load(Acquire)`.
    Alloc { k: usize, b: bool, i: usize },
    /// `send`: write the chunk bytes.
    Chunk { k: usize, b: bool, i: usize },
    /// `drop` step 1: `client_len[i].store(len, Relaxed)`.
    Len { k: usize, b: bool, i: usize },
    /// `drop` step 2: `client_owned[i].store(true, Relaxed)`.
    Own { k: usize, b: bool, i: usize },
    /// `drop` step 3: `cur_seq.fetch_add(1, Relaxed)`.
    Fadd { k: usize, b: bool, i: usize },
    /// `drop` step 4: `client_seq[i].store(seq, Release)`.
    Pub { k: usize, b: bool, i: usize, s: i64 },
    /// `drop` step 5: `while client_owned[i].load(Relaxed) {}`.
    Spin { k: usize, i: usize },
    /// Read uninitialized memory.
    Fault,
}

/// Receiver program counter, `t` the ticket held.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RPc {
    /// `request_ticket`: `seq.fetch_add(1, Relaxed)`.
    Init,
    /// `try_recv`: `client_seq[i].load(Acquire)`, compare with the ticket.
    Scan { t: i64, i: usize },
    /// `debug_assert!(client_owned[i].load(Relaxed))`.
    Own { t: i64, i: usize },
    /// `client_len[i].load(Relaxed)`.
    Len { t: i64, i: usize },
    /// Read the chunk bytes.
    Chunk { t: i64, i: usize, n: i64 },
    /// The callback returns `Ok` or `Err`.
    Cb { t: i64, i: usize, n: i64, p: i64 },
    /// `client_owned[i].store(false, Release)`, then a new ticket.
    Rel { t: i64, i: usize },
    /// The `debug_assert` failed, or uninitialized memory was read.
    Fault,
}

/// The sender: `SendPipe::alloc_buffer` and `ChunkWriter`.
#[derive(Clone, Debug)]
pub struct Sender {
    pub pc: SPc,
    /// Ghost: `(seq, payload, len)` of each published buffer.
    pub log: Vec<(i64, i64, i64)>,
}

impl Sender {
    /// One step of `Mempipe.sprog`.
    #[allow(unused_variables, unused_parens, unreachable_code, clippy::all)]
    pub fn step(&mut self, pipe: &Pipe, num_buffers: usize, num_messages: usize, pay: &dyn Fn(usize) -> i64, ln: &dyn Fn(usize) -> i64, choose: &mut dyn FnMut() -> bool) -> Status {
        let pc = self.pc;
        match pc {
            SPc::Start { k } => {
                if k < num_messages {
                    let b = choose();
                    self.pc = SPc::Alloc { k: k, b: b, i: 0 };
                } else {
                    return Status::Halted;
                }
            }
            SPc::Alloc { k, b, i } => {
                let v = pipe.client_owned[i].load(Ordering::Acquire) as i64;
                if v == 0 {
                    self.pc = SPc::Chunk { k: k, b: b, i: i };
                } else {
                    self.pc = SPc::Alloc { k: k, b: b, i: ((i + 1) % num_buffers) };
                }
            }
            SPc::Chunk { k, b, i } => {
                unsafe { pipe.write_chunk(i, pay(k)) };
                self.pc = SPc::Len { k: k, b: b, i: i };
            }
            SPc::Len { k, b, i } => {
                pipe.client_len[i].store(ln(k) as usize, Ordering::Relaxed);
                self.pc = SPc::Own { k: k, b: b, i: i };
            }
            SPc::Own { k, b, i } => {
                pipe.client_owned[i].store(true, Ordering::Relaxed);
                self.pc = SPc::Fadd { k: k, b: b, i: i };
            }
            SPc::Fadd { k, b, i } => {
                let s = pipe.cur_seq.fetch_add(1, Ordering::Relaxed) as i64;
                self.pc = SPc::Pub { k: k, b: b, i: i, s: s };
            }
            SPc::Pub { k, b, i, s } => {
                pipe.client_seq[i].store(s as u64, Ordering::Release);
                self.log.push((s, pay(k), ln(k)));
                self.pc = (if b { SPc::Spin { k: k, i: i } } else { SPc::Start { k: (k + 1) } });
            }
            SPc::Spin { k, i } => {
                let v = pipe.client_owned[i].load(Ordering::Relaxed) as i64;
                if v == 0 {
                    self.pc = SPc::Start { k: (k + 1) };
                } else {
                    self.pc = SPc::Spin { k: k, i: i };
                }
            }
            SPc::Fault => {
                return Status::Fault;
            }
        }
        Status::Running
    }
}

/// A receiver: `RecvPipe::request_ticket` and `RecvPipe::try_recv`.
#[derive(Clone, Debug)]
pub struct Receiver {
    pub pc: RPc,
    /// Ghost: `(ticket, payload, len)` of each accepted buffer.
    pub log: Vec<(i64, i64, i64)>,
}

impl Receiver {
    /// One step of `Mempipe.rprog`.
    #[allow(unused_variables, unused_parens, unreachable_code, clippy::all)]
    pub fn step(&mut self, pipe: &Pipe, num_buffers: usize, choose: &mut dyn FnMut() -> bool) -> Status {
        let pc = self.pc;
        match pc {
            RPc::Init => {
                let t = pipe.seq.fetch_add(1, Ordering::Relaxed) as i64;
                self.pc = RPc::Scan { t: t, i: 0 };
            }
            RPc::Scan { t, i } => {
                let s = pipe.client_seq[i].load(Ordering::Acquire) as i64;
                if s == t {
                    self.pc = RPc::Own { t: t, i: i };
                } else {
                    self.pc = RPc::Scan { t: t, i: ((i + 1) % num_buffers) };
                }
            }
            RPc::Own { t, i } => {
                let v = pipe.client_owned[i].load(Ordering::Relaxed) as i64;
                if v == 0 {
                    self.pc = RPc::Fault;
                    return Status::Fault;
                } else {
                    self.pc = RPc::Len { t: t, i: i };
                }
            }
            RPc::Len { t, i } => {
                let n = pipe.client_len[i].load(Ordering::Relaxed) as i64;
                self.pc = RPc::Chunk { t: t, i: i, n: n };
            }
            RPc::Chunk { t, i, n } => {
                match unsafe { pipe.read_chunk(i) } {
                    // uninitialized
                    None => {
                        self.pc = RPc::Fault;
                        return Status::Fault;
                    }
                    Some(p) => {
                        self.pc = RPc::Cb { t: t, i: i, n: n, p: p };
                    }
                }
            }
            RPc::Cb { t, i, n, p } => {
                let ok = choose();
                if ok {
                    self.log.push((t, p, n));
                    self.pc = RPc::Rel { t: t, i: i };
                } else {
                    self.pc = RPc::Scan { t: t, i: 0 };
                }
            }
            RPc::Rel { t, i } => {
                pipe.client_owned[i].store(false, Ordering::Release);
                self.pc = RPc::Init;
            }
            RPc::Fault => {
                return Status::Fault;
            }
        }
        Status::Running
    }
}
