import ORC11.Lemmas

/-!
# RC11 execution graphs of thread pools

The declarative model RC11 (Lahav, Vafeiadis, Kang, Hur, Dreyer, "Repairing
Sequential Consistency in C/C++11", PLDI 2017), without SC accesses and fences,
as used by the ORC11 appendix (§2.1: executions, consistency, races), for the
thread pools of `Program.lean`.

Representation choices (standard, but worth stating):

* Events are numbered `0, …, n - 1` in an order that extends program order
  (`sb`) and reads-from (`rf`): `sb` is the numbering within a thread, and a
  read's source has a smaller number. Such a numbering exists exactly when
  `sb ∪ rf` is acyclic, which is RC11's NO-THIN-AIR axiom; we represent
  consistent executions by such numberings.
* The initialization writes, one non-atomic write per location, are implicit
  events `init l`, before every other event in `sb`.
* The modification order of a location is given by ranks `ts`: `1` for the
  initialization and `2, 3, …` densely for the other writes. Any strict total
  order on a finite set has such a ranking.
* Each thread's events are generated by running its program: the thread's
  items (its events, in order, and the resolutions of its choices) must be a
  run of the program from its initial state, whose final state is recorded.
-/

namespace ORC11

namespace RC11

variable {Loc Val : Type}

/-- `event.v`-style labels: reads (the value read may be uninitialized),
writes, updates. -/
inductive Label (Loc Val : Type) where
  | R (l : Loc) (o : MemOrder) (v : Option Val)
  | W (l : Loc) (o : MemOrder) (v : Val)
  | U (l : Loc) (or ow : MemOrder) (vr vw : Val)

namespace Label

def loc : Label Loc Val → Loc
  | R l _ _ | W l _ _ | U l _ _ _ _ => l

/-- Reads and updates. -/
def IsRead : Label Loc Val → Prop
  | R .. | U .. => True
  | W .. => False

/-- Writes and updates. -/
def IsWrite : Label Loc Val → Prop
  | W .. | U .. => True
  | R .. => False

def IsUpdate : Label Loc Val → Prop
  | U .. => True
  | _ => False

/-- The value read. -/
def rval : Label Loc Val → Option (Option Val)
  | R _ _ v => some v
  | U _ _ _ vr _ => some (some vr)
  | W .. => none

/-- The value written. -/
def wval : Label Loc Val → Option Val
  | W _ _ v => some v
  | U _ _ _ _ vw => some vw
  | R .. => none

/-- Non-atomic accesses. -/
def IsNA : Label Loc Val → Prop
  | R _ o _ | W _ o _ => o = .na
  | U .. => False

/-- The write is atomic (`⊒ rlx`). -/
def AtomicW : Label Loc Val → Prop
  | W _ o _ => MemOrder.rlx ≤ o
  | U _ _ ow _ _ => MemOrder.rlx ≤ ow
  | R .. => False

/-- A release write (`⊒ rel`). -/
def RelW : Label Loc Val → Prop
  | W _ o _ => MemOrder.acqrel ≤ o
  | U _ _ ow _ _ => MemOrder.acqrel ≤ ow
  | R .. => False

/-- An acquire read (`⊒ acq`). -/
def AcqR : Label Loc Val → Prop
  | R _ o _ => MemOrder.acqrel ≤ o
  | U _ or _ _ _ => MemOrder.acqrel ≤ or
  | W .. => False

end Label

/-- A thread's item: one of its events, or the branch taken at a choice. -/
abbrev Item := ℕ ⊕ Bool

variable [DecidableEq Loc] [DecidableEq Val]

/-- Running one item of a thread: the instruction must match the event's
label (and a read continues with the value read), or be a choice. -/
def stepItem {S : Type} (p : S → Instr Loc Val S) (lab : ℕ → Label Loc Val) (s : S) :
    Item → Option S
  | .inr b => match p s with
    | .choose k => some (k b)
    | _ => none
  | .inl e => match p s, lab e with
    | .read l o k, .R l' o' v => if l = l' ∧ o = o' then some (k v) else none
    | .write l o v k, .W l' o' v' => if l = l' ∧ o = o' ∧ v = v' then some k else none
    | .update l or ow f k, .U l' or' ow' vr vw =>
      if l = l' ∧ or = or' ∧ ow = ow' ∧ vw = f vr then some (k vr) else none
    | _, _ => none

/-- Running a list of items. -/
def runItems {S : Type} (p : S → Instr Loc Val S) (lab : ℕ → Label Loc Val) :
    S → List Item → Option S
  | s, [] => some s
  | s, x :: xs => (stepItem p lab s x).bind fun s' => runItems p lab s' xs

variable {ι : Type} [DecidableEq ι] {S : ι → Type}

/-- An execution graph of the pool `prog` from local states `s0` and initial
values `v0` (appendix §2.1, Def. 8 "follows a trace"). -/
structure Exec (prog : (i : ι) → S i → Instr Loc Val (S i)) (s0 : (i : ι) → S i)
    (v0 : Loc → Option Val) where
  /-- number of events (besides the initialization) -/
  n : ℕ
  tid : ℕ → ι
  lab : ℕ → Label Loc Val
  /-- reads-from: the source of each read or update, `none` for the
  initialization of its location -/
  rf : ℕ → Option ℕ
  /-- modification order as ranks, per location -/
  ts : ℕ → ℕ
  /-- the threads that took any step -/
  active : Finset ι
  items : (i : ι) → List Item
  final : (i : ι) → S i
  run : ∀ i, runItems (prog i) lab (s0 i) (items i) = some (final i)
  inactive : ∀ i, i ∉ active → items i = []
  /-- a thread's items contain its events, in order -/
  itemsEv : ∀ i, (items i).filterMap Sum.getLeft? = (List.range n).filter (fun e => tid e = i)

section Graph

variable {prog : (i : ι) → S i → Instr Loc Val (S i)} {s0 : (i : ι) → S i}
  {v0 : Loc → Option Val}

/-- Events: the initialization of a location, or a numbered event. -/
inductive Ev (Loc : Type) where
  | init (l : Loc)
  | ev (e : ℕ)
  deriving DecidableEq

variable (G : Exec prog s0 v0)

namespace Exec

/-- The events of the graph. -/
def Mem : Ev Loc → Prop
  | .init _ => True
  | .ev e => e < G.n

def loc : Ev Loc → Loc
  | .init l => l
  | .ev e => (G.lab e).loc

def IsWrite : Ev Loc → Prop
  | .init _ => True
  | .ev e => e < G.n ∧ (G.lab e).IsWrite

def IsRead : Ev Loc → Prop
  | .init _ => False
  | .ev e => e < G.n ∧ (G.lab e).IsRead

def IsNA : Ev Loc → Prop
  | .init _ => True
  | .ev e => (G.lab e).IsNA

/-- Ranks in the modification order. -/
def tsE : Ev Loc → ℕ
  | .init _ => 1
  | .ev e => G.ts e

/-- Program order: initialization first, then the numbering within a thread. -/
def sb : Ev Loc → Ev Loc → Prop
  | .init _, .ev e => e < G.n
  | .ev a, .ev b => a < b ∧ b < G.n ∧ G.tid a = G.tid b
  | _, .init _ => False

/-- Reads-from. -/
def rfE : Ev Loc → Ev Loc → Prop
  | w, .ev e => e < G.n ∧ (G.lab e).IsRead ∧
      (match G.rf e with
       | none => w = .init (G.lab e).loc
       | some a => w = .ev a)
  | _, .init _ => False

/-- Modification order. -/
def mo (a b : Ev Loc) : Prop :=
  G.IsWrite a ∧ G.IsWrite b ∧ G.loc a = G.loc b ∧ G.tsE a < G.tsE b

/-- Reads-before. -/
def rb (a b : Ev Loc) : Prop := ∃ w, G.rfE w a ∧ G.mo w b

/-- Extended coherence order. -/
def eco : Ev Loc → Ev Loc → Prop := Relation.TransGen fun a b => G.rfE a b ∨ G.mo a b ∨ G.rb a b

/-- Release sequences: `[WU]; sb|loc?; [(WU)⊒rlx]; (rf; [U])*`. -/
def rs (a b : Ev Loc) : Prop :=
  G.IsWrite a ∧ ∃ c, (c = a ∨ (G.sb a c ∧ G.loc a = G.loc c)) ∧ G.IsWrite c ∧
    (match c with
     | .init _ => False
     | .ev e => (G.lab e).AtomicW) ∧
    Relation.ReflTransGen (fun x y => G.rfE x y ∧ ∃ e, y = .ev e ∧ (G.lab e).IsUpdate) c b

def RelW : Ev Loc → Prop
  | .init _ => False
  | .ev e => e < G.n ∧ (G.lab e).RelW

def AcqR : Ev Loc → Prop
  | .init _ => False
  | .ev e => e < G.n ∧ (G.lab e).AcqR

/-- Synchronizes-with, without fences:
`[E⊒rel]; rs; rf; [(RU)⊒acq]`. -/
def sw (a b : Ev Loc) : Prop := G.RelW a ∧ ∃ w, G.rs a w ∧ G.rfE w b ∧ G.AcqR b

/-- Happens-before. -/
def hb : Ev Loc → Ev Loc → Prop := Relation.TransGen fun a b => G.sb a b ∨ G.sw a b

/-- The graph is well formed: reads read a write of their location with its
value (or the initialization), the numbering extends `rf`, and the
modification order is a dense ranking of the writes of each location. -/
structure WF : Prop where
  rfSrc : ∀ e < G.n, (G.lab e).IsRead →
    match G.rf e with
    | none => (G.lab e).rval = some (v0 (G.lab e).loc)
    | some w => w < e ∧ (G.lab w).IsWrite ∧ (G.lab w).loc = (G.lab e).loc ∧
        (G.lab e).rval = some (G.lab w).wval
  tsW : ∀ e < G.n, (G.lab e).IsWrite → 2 ≤ G.ts e
  tsInj : ∀ a < G.n, ∀ b < G.n, (G.lab a).IsWrite → (G.lab b).IsWrite →
    (G.lab a).loc = (G.lab b).loc → G.ts a = G.ts b → a = b
  tsDense : ∀ e < G.n, (G.lab e).IsWrite → ∀ t, 2 ≤ t → t ≤ G.ts e →
    ∃ a < G.n, (G.lab a).IsWrite ∧ (G.lab a).loc = (G.lab e).loc ∧ G.ts a = t

/-- RC11 consistency without the SC axiom (appendix Def. 5, plus RC11's
atomicity axiom). NO-THIN-AIR holds by the numbering. -/
structure Consistent : Prop where
  wf : G.WF
  /-- COHERENCE: `hb; eco?` is irreflexive -/
  hbIrrefl : ∀ a, ¬ G.hb a a
  coherence : ∀ a b, G.hb a b → ¬ G.eco b a
  /-- ATOMICITY: an update reads the write right before it in `mo`. With
  updates as single events this is `rmw ∩ (rb; mo) = ∅` together with `mo`
  ordering an update after its source, which RC11 gets from coherence when an
  update is a read and a write related by `sb`. -/
  atomicity : ∀ e < G.n, (G.lab e).IsUpdate → ∀ w, G.rfE w (.ev e) →
    G.mo w (.ev e) ∧ ∀ x, ¬ (G.mo w x ∧ G.mo x (.ev e))

/-- Conflicting events (appendix Def. 9). -/
def Conflict (a b : Ev Loc) : Prop :=
  G.Mem a ∧ G.Mem b ∧ a ≠ b ∧ G.loc a = G.loc b ∧ (G.IsWrite a ∨ G.IsWrite b)

/-- Races (appendix Def. 10). -/
def Race (a b : Ev Loc) : Prop :=
  G.Conflict a b ∧ ¬ G.hb a b ∧ ¬ G.hb b a ∧ (G.IsNA a ∨ G.IsNA b)

/-- The graph is racy. -/
def Racy : Prop := ∃ a b, G.Race a b

/-! ## Basic facts -/

variable {G}

/-- `hb` or equal. -/
abbrev hbS (a b : Ev Loc) : Prop := Relation.ReflGen G.hb a b

theorem rfE_ev {w : Ev Loc} {e : ℕ} (h : G.rfE w (.ev e)) :
    e < G.n ∧ (G.lab e).IsRead ∧
      (match G.rf e with
       | none => w = .init (G.lab e).loc
       | some a => w = .ev a) := h

theorem not_rfE_init {w : Ev Loc} {l : Loc} : ¬ G.rfE w (.init l) := fun h => h

theorem rfE_tgt {w r : Ev Loc} (h : G.rfE w r) : ∃ e, r = .ev e ∧ e < G.n ∧ (G.lab e).IsRead := by
  cases r with
  | init l => exact absurd h not_rfE_init
  | ev e => exact ⟨e, rfl, h.1, h.2.1⟩

/-- The source of a read is a write of its location, numbered before it. -/
theorem rfE_src (hwf : G.WF) {w : Ev Loc} {e : ℕ} (h : G.rfE w (.ev e)) :
    G.IsWrite w ∧ G.loc w = (G.lab e).loc ∧ (∀ a, w = .ev a → a < e) := by
  obtain ⟨he, hr, hw⟩ := h
  have := hwf.rfSrc e he hr
  cases hrf : G.rf e with
  | none =>
    rw [hrf] at hw; subst hw
    exact ⟨trivial, rfl, fun a h => by cases h⟩
  | some a =>
    rw [hrf] at hw this; subst hw
    obtain ⟨h1, h2, h3, -⟩ := this
    exact ⟨⟨by omega, h2⟩, h3, fun a' h => by cases h; exact h1⟩

theorem sb_tgt {a b : Ev Loc} (h : G.sb a b) :
    ∃ e, b = .ev e ∧ e < G.n ∧ ∀ x, a = .ev x → x < e := by
  cases a <;> cases b
  · exact absurd h id
  · exact ⟨_, rfl, h, fun x hx => by cases hx⟩
  · exact absurd h id
  · exact ⟨_, rfl, h.2.1, fun x hx => by cases hx; exact h.1⟩

/-- Release sequences move forward in the numbering. -/
theorem rs_tgt (hwf : G.WF) {a b : Ev Loc} (h : G.rs a b) :
    ∃ e, b = .ev e ∧ e < G.n ∧ ∀ x, a = .ev x → x ≤ e := by
  obtain ⟨-, c, hc, hcw, hca, hchain⟩ := h
  -- the head `c` is a numbered event after `a`
  obtain ⟨ec, rfl, hecn, hac⟩ : ∃ ec, c = .ev ec ∧ ec < G.n ∧ ∀ x, a = .ev x → x ≤ ec := by
    cases c with
    | init l => exact absurd hca id
    | ev ec =>
      refine ⟨ec, rfl, hcw.1, fun x hx => ?_⟩
      rcases hc with hc | ⟨hc, -⟩
      · rw [hx] at hc; cases hc; exact le_rfl
      · obtain ⟨e, he, -, hlt⟩ := sb_tgt hc
        cases he; exact (hlt x hx).le
  clear hc hca hcw
  induction hchain with
  | refl => exact ⟨ec, rfl, hecn, hac⟩
  | tail _ hstep ih =>
    obtain ⟨e1, rfl, -, h1⟩ := ih
    obtain ⟨hr, e2, rfl, -⟩ := hstep
    have := (rfE_src hwf hr).2.2 e1 rfl
    exact ⟨e2, rfl, hr.1, fun x hx => (h1 x hx).trans this.le⟩

theorem sw_tgt (hwf : G.WF) {a b : Ev Loc} (h : G.sw a b) :
    ∃ x e, a = .ev x ∧ b = .ev e ∧ x < e ∧ e < G.n := by
  obtain ⟨hrel, w, hrs, hrf, hacq⟩ := h
  cases a with
  | init l => exact absurd hrel id
  | ev x =>
    obtain ⟨ew, rfl, -, hle⟩ := rs_tgt hwf hrs
    obtain ⟨e, rfl, hen, -⟩ := rfE_tgt hrf
    exact ⟨x, e, rfl, rfl, (hle x rfl).trans_lt ((rfE_src hwf hrf).2.2 ew rfl), hen⟩

/-- Happens-before goes forward in the numbering. -/
theorem hb_tgt (hwf : G.WF) {a b : Ev Loc} (h : G.hb a b) :
    ∃ e, b = .ev e ∧ e < G.n ∧ ∀ x, a = .ev x → x < e := by
  induction h with
  | single hs =>
    rcases hs with hs | hs
    · exact sb_tgt hs
    · obtain ⟨x, e, rfl, rfl, hlt, hen⟩ := sw_tgt hwf hs
      exact ⟨e, rfl, hen, fun x' hx' => by cases hx'; exact hlt⟩
  | tail _ hs ih =>
    obtain ⟨e1, rfl, -, h1⟩ := ih
    rcases hs with hs | hs
    · obtain ⟨e2, rfl, hen, h2⟩ := sb_tgt hs
      exact ⟨e2, rfl, hen, fun x hx => (h1 x hx).trans (h2 e1 rfl)⟩
    · obtain ⟨x, e2, hx, rfl, hlt, hen⟩ := sw_tgt hwf hs
      cases hx
      exact ⟨e2, rfl, hen, fun x' hx' => (h1 x' hx').trans hlt⟩

theorem hb_lt (hwf : G.WF) {a b : ℕ} (h : G.hb (.ev a) (.ev b)) : a < b := by
  obtain ⟨e, he, -, hlt⟩ := hb_tgt hwf h
  cases he; exact hlt a rfl

theorem not_hb_init (hwf : G.WF) {a : Ev Loc} {l : Loc} : ¬ G.hb a (.init l) := fun h => by
  obtain ⟨e, he, -⟩ := hb_tgt hwf h; cases he

theorem hbS_lt (hwf : G.WF) {a b : ℕ} (h : G.hbS (.ev a) (.ev b)) : a ≤ b := by
  rcases h with _ | h
  · exact le_rfl
  · exact (hb_lt hwf h).le

theorem hb_trans {a b c : Ev Loc} (h1 : G.hb a b) (h2 : G.hb b c) : G.hb a c :=
  Relation.TransGen.trans h1 h2

theorem hbS_hb {a b c : Ev Loc} (h1 : G.hbS a b) (h2 : G.hb b c) : G.hb a c := by
  rcases h1 with _ | h1
  · exact h2
  · exact hb_trans h1 h2

theorem hb_hbS {a b c : Ev Loc} (h1 : G.hb a b) (h2 : G.hbS b c) : G.hb a c := by
  rcases h2 with _ | h2
  · exact h1
  · exact hb_trans h1 h2

theorem hbS_trans {a b c : Ev Loc} (h1 : G.hbS a b) (h2 : G.hbS b c) : G.hbS a c := by
  rcases h1 with _ | h1
  · exact h2
  · exact .single (hb_hbS h1 h2)

theorem hb_of_sb {a b : Ev Loc} (h : G.sb a b) : G.hb a b := .single (Or.inl h)

theorem hb_of_sw {a b : Ev Loc} (h : G.sw a b) : G.hb a b := .single (Or.inr h)

/-- Program order within a thread. -/
theorem hb_of_tid {a b : ℕ} (hab : a < b) (hb : b < G.n) (ht : G.tid a = G.tid b) :
    G.hb (.ev a) (.ev b) :=
  hb_of_sb ⟨hab, hb, ht⟩

/-- The initialization happens before everything. -/
theorem hb_init {l : Loc} {e : ℕ} (he : e < G.n) : G.hb (.init l) (.ev e) :=
  hb_of_sb he

/-- An atomic write heads its own release sequence. -/
theorem rs_refl {e : ℕ} (he : e < G.n) (hw : (G.lab e).IsWrite) (ha : (G.lab e).AtomicW) :
    G.rs (.ev e) (.ev e) :=
  ⟨⟨he, hw⟩, .ev e, Or.inl rfl, ⟨he, hw⟩, ha, .refl⟩

/-- Release sequences continue through updates. -/
theorem rs_update {h w : Ev Loc} {e : ℕ} (hrs : G.rs h w) (hrf : G.rfE w (.ev e))
    (hu : (G.lab e).IsUpdate) : G.rs h (.ev e) := by
  obtain ⟨hh, c, hc, hcw, hca, hchain⟩ := hrs
  exact ⟨hh, c, hc, hcw, hca, hchain.tail ⟨hrf, e, rfl, hu⟩⟩

/-! ## Consequences of coherence and atomicity -/

variable (hc : G.Consistent)
include hc

/-- A thread that has seen `w'` (it happens before, or is read by an event
that happens before) cannot then read a write `mo`-before `w'`. -/
theorem coh_read {w' src : Ev Loc} {e : ℕ} (hrf : G.rfE src (.ev e))
    (hseen : G.hb w' (.ev e) ∨ ∃ r, G.rfE w' r ∧ G.hb r (.ev e)) :
    ¬ G.mo src w' := by
  intro hmo
  have hrb : G.rb (.ev e) w' := ⟨src, hrf, hmo⟩
  rcases hseen with h | ⟨r, hr, h⟩
  · exact hc.coherence _ _ h (.single (Or.inr (Or.inr hrb)))
  · exact hc.coherence _ _ h (.tail (.single (Or.inr (Or.inr hrb))) (Or.inl hr))

/-- A thread that has seen `w'` cannot then write `mo`-before `w'`. -/
theorem coh_write {w' : Ev Loc} {e : ℕ}
    (hseen : G.hb w' (.ev e) ∨ ∃ r, G.rfE w' r ∧ G.hb r (.ev e)) :
    ¬ G.mo (.ev e) w' := by
  intro hmo
  rcases hseen with h | ⟨r, hr, h⟩
  · exact hc.coherence _ _ h (.single (Or.inr (Or.inl hmo)))
  · exact hc.coherence _ _ h (.tail (.single (Or.inr (Or.inl hmo))) (Or.inl hr))

/-- `hb` between writes of a location orders them in `mo`. -/
theorem coh_hb_mo {a b : Ev Loc} (hab : G.hb a b) : ¬ G.mo b a := fun hmo =>
  hc.coherence _ _ hab (.single (Or.inr (Or.inl hmo)))

/-- An update's rank is right after its source's. -/
theorem ts_update {w : Ev Loc} {e : ℕ} (he : e < G.n) (hu : (G.lab e).IsUpdate)
    (hrf : G.rfE w (.ev e)) : G.ts e = G.tsE w + 1 := by
  obtain ⟨hmo, himm⟩ := hc.atomicity e he hu w hrf
  obtain ⟨hw, -, hloc, hlt⟩ := hmo
  have hwrite : (G.lab e).IsWrite := by
    revert hu; cases G.lab e <;> simp [Label.IsUpdate, Label.IsWrite]
  have hlt' : G.tsE w < G.ts e := hlt
  have h2 : 2 ≤ G.tsE w + 1 := by
    cases w with
    | init l => simp [tsE]
    | ev x => have := hc.wf.tsW x hw.1 hw.2; simp [tsE]; omega
  by_contra hne
  obtain ⟨a, ha, haw, hal, hat⟩ := hc.wf.tsDense e he hwrite (G.tsE w + 1) h2 (by omega)
  apply himm (.ev a)
  refine ⟨⟨hw, ⟨ha, haw⟩, ?_, ?_⟩, ⟨⟨ha, haw⟩, ⟨he, hwrite⟩, ?_, ?_⟩⟩
  · show G.loc w = (G.lab a).loc; rw [hal]; exact hloc
  · show G.tsE w < G.ts a; omega
  · show (G.lab a).loc = (G.lab e).loc; exact hal
  · show G.ts a < G.ts e; omega

end Exec

end Graph

end RC11

end ORC11
